services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8790 --proxy-headers
    volumes:
      - .:/code
      - type: bind
        source: /mnt/ssd/faiss_data
        target: /mnt/ssd/faiss_data
      - type: bind
        source: /mnt/ssd/faiss_data/mmap
        target: /mnt/ssd/faiss_data/mmap
    ports:
      - "8790:8790"
