services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8789 --proxy-headers
    volumes:
      - .:/code
      - type: bind
        source: /mnt/ssd/ecco_faiss/data
        target: /mnt/ssd/ecco_faiss/data
    ports:
      - "8789:8789"
